#pragma once

#include <Windows.h>

namespace Win33 {
    
    enum class VirtualKeyCode : DWORD {
        Backspace          = VK_BACK,
        Tab                = VK_TAB,
        Enter              = VK_RETURN,
        Shift              = VK_SHIFT,
        Control            = VK_CONTROL,
        Alt                = VK_MENU,
        Pause              = VK_PAUSE,
        CapsLock           = VK_CAPITAL,
        Escape             = VK_ESCAPE,
        Spacebar           = VK_SPACE,
        PageUp             = VK_PRIOR,
        PageDown           = VK_NEXT,
        End                = VK_END,
        Home               = VK_HOME,
        LeftArrow          = VK_LEFT,
        UpArrow            = VK_UP,
        RightArrow         = VK_RIGHT,
        DownArrow          = VK_DOWN,
        PrintScreen        = VK_SNAPSHOT,
        Insert             = VK_INSERT,
        Delete             = VK_DELETE,
        Zero               = 0x30,
        One                = 0x31,
        Two                = 0x32,
        Three              = 0x33,
        Four               = 0x34,
        Five               = 0x35,
        Six                = 0x36,
        Seven              = 0x37,
        Eight              = 0x38,
        Nine               = 0x39,
        A                  = 0x41,
        B                  = 0x42,
        C                  = 0x43,
        D                  = 0x44,
        E                  = 0x45,
        F                  = 0x46,
        G                  = 0x47,
        H                  = 0x48,
        I                  = 0x49,
        J                  = 0x4A,
        K                  = 0x4B,
        L                  = 0x4C,
        M                  = 0x4D,
        N                  = 0x4E,
        O                  = 0x4F,
        P                  = 0x50,
        Q                  = 0x51,
        R                  = 0x52,
        S                  = 0x53,
        T                  = 0x54,
        U                  = 0x55,
        V                  = 0x56,
        W                  = 0x57,
        X                  = 0x58,
        Y                  = 0x59,
        Z                  = 0x5A,
        LeftWindows        = VK_LWIN,
        RightWindows       = VK_RWIN,
        NumpadZero         = VK_NUMPAD0,
        NumpadOne          = VK_NUMPAD1,
        NumpadTwo          = VK_NUMPAD2,
        NumpadThree        = VK_NUMPAD3,
        NumpadFour         = VK_NUMPAD4,
        NumpadFive         = VK_NUMPAD5,
        NumpadSix          = VK_NUMPAD6,
        NumpadSeven        = VK_NUMPAD7,
        NumpadEight        = VK_NUMPAD8,
        NumpadNine         = VK_NUMPAD9,
        NumpadMultiply     = VK_MULTIPLY,
        NumpadAdd          = VK_ADD,
        NumpadSeperator    = VK_SEPARATOR,
        NumpadSubtract     = VK_SUBTRACT,
        NumpadDecimal      = VK_DECIMAL,
        NumpadDivide       = VK_DIVIDE,
        F1                 = VK_F1,
        F2                 = VK_F2,
        F3                 = VK_F3,
        F4                 = VK_F4,
        F5                 = VK_F5,
        F6                 = VK_F6,
        F7                 = VK_F7,
        F8                 = VK_F8,
        F9                 = VK_F9,
        F10                = VK_F10,
        F11                = VK_F11,
        F12                = VK_F12,
        NumLock            = VK_NUMLOCK,
        ScrollLock         = VK_SCROLL,
        LeftShift          = VK_LSHIFT,
        RightShift         = VK_RSHIFT,
        LeftControl        = VK_LCONTROL,
        RightControl       = VK_RCONTROL,
        LeftAlt            = VK_LMENU,
        RightAlt           = VK_RMENU,
        SemiColon          = VK_OEM_1,
        Plus               = VK_OEM_PLUS,
        Comma              = VK_OEM_COMMA,
        Minus              = VK_OEM_MINUS,
        Period             = VK_OEM_PERIOD,
        QuestionMark       = VK_OEM_2,
        Tilde              = VK_OEM_3,
        OpenSquareBracket  = VK_OEM_4,
        Pipe               = VK_OEM_5,
        CloseSquareBracket = VK_OEM_6,
        SingleQuote        = VK_OEM_7
    };
    
    enum class Key : int {
        Unknown,
        Escape,
        F1,
        F2,
        F3,
        F4,
        F5,
        F6,
        F7,
        F8,
        F9,
        F10,
        F11,
        F12,
        Tick,
        Tilde,
        One,
        ExclamationPoint,
        Two,
        AtSymbol,
        Three,
        Hash,
        Four,
        DollarSign,
        Five,
        Percent,
        Six,
        Caret,
        Seven,
        Ampersand,
        Eight,
        Asterisk,
        Nine,
        OpenBracket,
        Zero,
        CloseBracket,
        Minus,
        Underscore,
        Equals,
        Plus,
        Backspace,
        Tab,
        Q,
        W,
        E,
        R,
        T,
        Y,
        U,
        I,
        O,
        P,
        OpenSquareBracket,
        OpenCurlyBrace,
        CloseSquareBracket,
        CloseCurlyBrace,
        BackSlash,
        Pipe,
        CapsLock,
        A,
        S,
        D,
        F,
        G,
        H,
        J,
        K,
        L,
        SemiColon,
        Colon,
        SingleQuote,
        DoubleQuote,
        Enter,
        LeftShift,
        Z,
        X,
        C,
        V,
        B,
        N,
        M,
        Comma,
        LessThan,
        Period,
        GreaterThan,
        Slash,
        QuestionMark,
        RightShift,
        LeftControl,
        LeftWindows,
        LeftAlt,
        Spacebar,
        RightAlt,
        RightWindows,
        Menu,
        RightControl,
        PrintScreen,
        MagicSysRq,
        ScrollLock,
        Pause,
        Break,
        Insert,
        Home,
        PageUp,
        Delete,
        End,
        PageDown,
        LeftArrow,
        UpArrow,
        DownArrow,
        RightArrow,
        NumLock,
        NumpadDivide,
        NumpadMultiply,
        NumpadSubtract,
        NumpadSeven,
        NumpadEight,
        NumpadNine,
        NumpadFour,
        NumpadFive,
        NumpadSix,
        NumpadAdd,
        NumpadOne,
        NumpadTwo,
        NumpadThree,
        NumpadZero,
        NumpadDecimal,
        NumpadEnter
    };
    
    Key toKey( VirtualKeyCode keyCode );
    
};